In [1]:
from urllib.parse import urlencode, quote_plus
from urllib import parse
import requests as rq
import json 
import pandas as pd 
from pandas.io.json import json_normalize
from json import JSONDecodeError

In [6]:
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'

In [9]:
data = {}
header = ['stnId', 'stnNm', 'tm', 'avgTa', 'minTa', 'minTaHrmt', 'maxTa',
       'maxTaHrmt', 'mi10MaxRn', 'mi10MaxRnHrmt', 'hr1MaxRn', 'hr1MaxRnHrmt',
       'sumRnDur', 'sumRn', 'maxInsWs', 'maxInsWsWd', 'maxInsWsHrmt', 'maxWs',
       'maxWsWd', 'maxWsHrmt', 'avgWs', 'hr24SumRws', 'maxWd', 'avgTd',
       'minRhm', 'minRhmHrmt', 'avgRhm', 'avgPv', 'avgPa', 'maxPs',
       'maxPsHrmt', 'minPs', 'minPsHrmt', 'avgPs', 'ssDur', 'sumSsHr',
       'hr1MaxIcsrHrmt', 'hr1MaxIcsr', 'sumGsr', 'ddMefs', 'ddMefsHrmt',
       'ddMes', 'ddMesHrmt', 'sumDpthFhsc', 'avgTca', 'avgLmac', 'avgTs',
       'minTg', 'avgCm5Te', 'avgCm10Te', 'avgCm20Te', 'avgCm30Te', 'avgM05Te',
       'avgM10Te', 'avgM15Te', 'avgM30Te', 'avgM50Te', 'sumLrgEv', 'sumSmlEv',
       'n99Rn', 'iscs', 'sumFogDur']
region_code = [90,93,95,98,99,100,101,102,104,105,106,108,112,114,115,119,121,127,129,130,131,133,135,136,
               137,138,140,143,146,152,155,156,159,162,165,168,169,170,172,174,177,184,185,188,189,192,212,
               216,217,221,226,232,235,236,238,239,243,244,245,247,248,251,252,253,254,255,257,258,259,260,
               261,262,263,264,266,268,271,272,273,276,277,278,279,281,283,284,285,288,289,294,295]
df = pd.DataFrame(columns=header)

In [10]:
for region in region_code:
    for year in range(2021,2022):
        start_month = str(year) + "0605"
        end_month = str(year) +"0713"
        for page in range(1,8):
            queryParams = '?' + parse.urlencode({ parse.quote_plus('ServiceKey') : 'VFK/ktW6424VcSedQvSsbOj745JgyeOZ9uyna9yP8uNQX7CMlQzoAlc+6eNdEre+mDUUtoP7l2MMUonKrjXnTg==',
                                           parse.quote_plus('pageNo') : page,
                                           parse.quote_plus('numOfRows') : '10',
                                           parse.quote_plus('dataType') : 'JSON',
                                           parse.quote_plus('dataCd') : 'ASOS',
                                           parse.quote_plus('dateCd') : 'DAY',
                                           parse.quote_plus('startDt') : start_month,
                                           parse.quote_plus('endDt') : end_month,
                                           parse.quote_plus('stnIds') : region })
            request = rq.get(url + queryParams)
            try:
                data = request.json()
                new_df = pd.json_normalize(data['response']['body']['items']['item'])
            except (JSONDecodeError,KeyError):
                pass
            else:
                print(region," ",year)
                df = df.append(new_df, ignore_index = True)

90   2021
90   2021
90   2021
90   2021
93   2021
93   2021
93   2021
93   2021
95   2021
95   2021
95   2021
95   2021
98   2021
98   2021
98   2021
98   2021
99   2021
99   2021
99   2021
99   2021
100   2021
100   2021
100   2021
100   2021
101   2021
101   2021
101   2021
101   2021
102   2021
102   2021
102   2021
102   2021
104   2021
104   2021
104   2021
104   2021
105   2021
105   2021
105   2021
105   2021
106   2021
106   2021
106   2021
106   2021
108   2021
108   2021
108   2021
108   2021
112   2021
112   2021
112   2021
112   2021
114   2021
114   2021
114   2021
114   2021
115   2021
115   2021
115   2021
115   2021
119   2021
119   2021
119   2021
119   2021
121   2021
121   2021
121   2021
121   2021
127   2021
127   2021
127   2021
127   2021
129   2021
129   2021
129   2021
129   2021
130   2021
130   2021
130   2021
130   2021
131   2021
131   2021
131   2021
131   2021
133   2021
133   2021
133   2021
133   2021
135   2021
135   2021
135   2021
135   2021
136   2021
136   2021
136   2021
136   2021
137   2021
137   2021
137   2021
137   2021
138   2021
138   2021
138   2021
138   2021
140   2021
140   2021
140   2021
140   2021
143   2021
143   2021
143   2021
143   2021
146   2021
146   2021
146   2021
146   2021
152   2021
152   2021
152   2021
152   2021
155   2021
155   2021
155   2021
155   2021
156   2021
156   2021
156   2021
156   2021
159   2021
159   2021
159   2021
159   2021
162   2021
162   2021
162   2021
162   2021
165   2021
165   2021
165   2021
165   2021
168   2021
168   2021
168   2021
168   2021
169   2021
169   2021
169   2021
169   2021
170   2021
170   2021
170   2021
170   2021
172   2021
172   2021
172   2021
172   2021
174   2021
174   2021
174   2021
174   2021
177   2021
177   2021
177   2021
177   2021
184   2021
184   2021
184   2021
184   2021
185   2021
185   2021
185   2021
185   2021
188   2021
188   2021
188   2021
188   2021
189   2021
189   2021
189   2021
189   2021
192   2021
192   2021
192   2021
192   2021
212   2021
212   2021
212   2021
212   2021
216   2021
216   2021
216   2021
216   2021
217   2021
217   2021
217   2021
217   2021
221   2021
221   2021
221   2021
221   2021
226   2021
226   2021
226   2021
226   2021
232   2021
232   2021
232   2021
232   2021
235   2021
235   2021
235   2021
235   2021
236   2021
236   2021
236   2021
236   2021
238   2021
238   2021
238   2021
238   2021
239   2021
239   2021
239   2021
239   2021
243   2021
243   2021
243   2021
243   2021
244   2021
244   2021
244   2021
244   2021
245   2021
245   2021
245   2021
245   2021
247   2021
247   2021
247   2021
247   2021
248   2021
248   2021
248   2021
248   2021
251   2021
251   2021
251   2021
251   2021
252   2021
252   2021
252   2021
252   2021
253   2021
253   2021
253   2021
253   2021
254   2021
254   2021
254   2021
254   2021
255   2021
255   2021
255   2021
255   2021
257   2021
257   2021
257   2021
257   2021
258   2021
258   2021
258   2021
258   2021
259   2021
259   2021
259   2021
259   2021
260   2021
260   2021
260   2021
260   2021
261   2021
261   2021
261   2021
261   2021
262   2021
262   2021
262   2021
262   2021
263   2021
263   2021
263   2021
263   2021
264   2021
264   2021
264   2021
264   2021
266   2021
266   2021
266   2021
266   2021
268   2021
268   2021
268   2021
268   2021
271   2021
271   2021
271   2021
271   2021
272   2021
272   2021
272   2021
272   2021
273   2021
273   2021
273   2021
273   2021
276   2021
276   2021
276   2021
276   2021
277   2021
277   2021
277   2021
277   2021
278   2021
278   2021
278   2021
278   2021
279   2021
279   2021
279   2021
279   2021
281   2021
281   2021
281   2021
281   2021
283   2021
283   2021
283   2021
283   2021
284   2021
284   2021
284   2021
284   2021
285   2021
285   2021
285   2021
285   2021
288   2021
288   2021
288   2021
288   2021
289   2021
289   2021
289   2021
289   2021
294   2021
294   2021
294   2021
294   2021
295   2021
295   2021
295   2021
295   2021

In [11]:
df

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
0,90,속초,2021-06-05,23.2,19.6,529,28.2,1615,,,...,,,,,,,,,,
1,90,속초,2021-06-06,22.9,19.0,2202,27.4,1617,,,...,,,,,,,,,,
2,90,속초,2021-06-07,24.5,19.9,555,30.0,1150,0,,...,,,,,,,,,,
3,90,속초,2021-06-08,20.2,17.6,2315,23.7,1302,0,43,...,,,,,,,,,,
4,90,속초,2021-06-09,19.9,17.0,457,23.2,1025,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3544,295,남해,2021-07-09,26.1,23.8,456,29.7,1221,3,1,...,,,,,,,,,,
3545,295,남해,2021-07-10,25.9,22.2,510,29.2,1200,,,...,,,,,,,,,,
3546,295,남해,2021-07-11,26.7,22.7,215,31.2,1549,,,...,,,,,,,,,,
3547,295,남해,2021-07-12,27.5,25.0,115,31.3,1116,,,...,,,,,,,,,,
3548,295,남해,2021-07-13,27.5,25.3,16,30.6,1429,,,...,,,,,,,,,,

In [12]:
df.to_csv("./data1.txt",sep = ',',encoding='utf-8-sig',index=False)